// export  const  STRIPE_PUBLISHABLEKEY= "pk_test_51Nc4BESHvLfWLlsnjp1azv1ARWB9QUqmJsI7Zn9ZouJDJxCmr4Z7uPStA9o5JPEXvDEoTYZUGcy8A9SXcnArsaMI00xf8UlDD0";

//   export const STRIPE_SECRET_KEY="sk_test_51Nc4BESHvLfWLlsnGQQYA5JcxXAdqj679CWVZINR67mg8SdMqgcpMUwGIjWQmVY1DZpOIgxzdsAyIBAou6EE5xeI00BLRKHAK7";



// const RAZORPAY_PUBLISHBALE_KEY = "rzp_test_e684qjpT2GcMb6"

// const RAZORPAY_SECRET_KEY = "ScCWY3yjIf9O8qdljfazfmEk"